urls:
  - url: "https://account.simplepractice.com/"
    expected_keyword: "SimplePractice"
  - url: "https://example.com/"

slack_webhook_url: ""
email:
  host: ""
  port: 587
  username: ""
  password: ""
  recipient: ""
db_file: "status.db"
check_interval_minutes: 5
slow_threshold: 2.0
timeout_seconds: 15
