name: "SimplePractice Monitor"

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes; adjust to your preference
  workflow_dispatch:

jobs:
  check_sp:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run SimplePractice Monitor
        run: |
          python monitor_simplepractice.py

      # --- Optional: If you want to see these files in the Action's artifacts:
      #
      # - name: Upload status artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: status-files
      #     path: |
      #       status.json
      #       index.html
      #
      # --- Optional: If you want to commit them back to your repo:
      #
      # - name: Configure Git
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #
      # - name: Commit changes
      #   run: |
      #     git add status.json index.html
      #     git commit -m "Update status artifacts [skip ci]"
      #     git push
